### ISSUE TITLE
官网给的plugins/alerter/WebankIMS/conf/plugin.properties 主要是修改exec服务器，但实际上是web服务器发送邮件

### ISSUE THREAD

**Issue by Yiutto** [WeBankFinTech/Schedulis#102]
alerter.class=com.azkaban.webank.WeBankAlerter
alerter.name=email

这是web服务器配置， exec不用配置也行

**Comment by James23Wang** [comment]
> 

执行服务 executor 也存在告警逻辑，如需要执行阶段的告警也许配置
