### ISSUE TITLE
任务类型 'flow' 未识别.

### ISSUE THREAD

**Issue by Yiutto** [WeBankFinTech/Schedulis#105]
![image](https://user-images.githubusercontent.com/12077317/185017309-c0db992d-4468-46de-95c4-b5eb8ba9a588.png)
任务出现偶发的不识别工作流flow，任务配置了重试也有可能失败

**Comment by Yiutto** [comment]
![图片](https://user-images.githubusercontent.com/12077317/192927942-aee02a59-19ee-4678-aaa5-28720b789a1b.png)

**Comment by Yiutto** [comment]
![3e53bbc51b0197c6f3c5ea0105b399d](https://user-images.githubusercontent.com/12077317/192928570-1b480fb9-2671-4573-9b06-42911ab77b64.jpg)

**Comment by James23Wang** [comment]
#110 This PR has solved the issue, please try version 0.7.1.
