### ISSUE TITLE
部署方式太复杂

### ISSUE THREAD

**Issue by Vinsmoke66** [WeBankFinTech/Schedulis#50]
比起exchangis来说，schedulis部署方式太麻烦了

**Comment by SelfImpr001** [comment]
我们正在优化部署脚本，用以解决在部署的时候配置文件多而杂的问题

**Comment by Vinsmoke66** [comment]
> 我们正在优化部署脚本，用以解决在部署的时候配置文件多而杂的问题

非常感谢
