### ISSUE TITLE
【schedulis-release-0.6.2】登录成功后点击其他菜单或功能按钮，就跳转到登录页面

### ISSUE THREAD

**Issue by windwhisper-i** [WeBankFinTech/Schedulis#85]
![image](https://user-images.githubusercontent.com/73170854/160992258-518841fb-fbdf-408d-a48c-3d4855da0712.png)
![image](https://user-images.githubusercontent.com/73170854/160992291-2a2f3540-bbde-49e6-8816-2e7d5c77557f.png)
返回：{"error":"session"}

**Comment by xcdh123456** [comment]
将web/conf/azkaban.properties文件中session.time.to.live=300注释掉就可以解决

**Comment by windwhisper-i** [comment]
可以了谢谢
