### ISSUE TITLE
安装Schedulis0.6.2版本并成功启动，使用默认账号登录后，点击任意连接直接返回登录页面

### ISSUE THREAD

**Issue by christlee2258** [WeBankFinTech/Schedulis#87]
![image](https://user-images.githubusercontent.com/103922/163512109-fe619cbe-5ca9-4092-8e64-c0b8df843042.png)
默认登录账号信息如下：
username : superadmin
pwd : Abcd1234

单击任意顶部菜单链接，直接返回到登录页面，详见如下视频

https://user-images.githubusercontent.com/103922/163512461-a42a1072-175c-41d9-99be-3abcc987f2af.mp4

**Comment by James23Wang** [comment]
请修改 Web Server 目录下 conf/azkaban.properties 中 session.time.to.live 配置，将其数值改大或者删去这项配置（即采用代码中的默认配置）
